# Generated by Django 5.2.1 on 2025-07-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrera',
            table='carreradb',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='cursodb',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='departamentodb',
        ),
        migrations.AlterModelTable(
            name='perfil',
            table='perfildb',
        ),
    ]
