# Generated by Django 5.2.1 on 2025-07-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_carrera_table_alter_curso_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='carreras',
            field=models.ManyToManyField(blank=True, db_table='perfil_carreras', related_name='perfiles', to='authentication.carrera'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cursos',
            field=models.ManyToManyField(blank=True, db_table='perfil_cursos', related_name='perfiles', to='authentication.curso'),
        ),
    ]
