# Generated by Django 5.2.1 on 2025-06-05 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaVirtualDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('en_uso', 'En Uso'), ('en_mantenimiento', 'En_Mantenimiento'), ('inactiva', 'Inactiva'), ('bloqueada', 'Bloqueada')], default='disponible', max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Aula Virtual',
                'verbose_name_plural': 'Aulas Virtuales',
                'db_table': 'aula_virtualdb',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CarreraDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=3, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'carreradb',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DepartamentoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('jefe', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentodb',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CursoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion', models.PositiveIntegerField(blank=True, help_text='Duración en horas', null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.carreradb')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursodb',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='carreradb',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.departamentodb'),
        ),
        migrations.CreateModel(
            name='ProfesorDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('carreras', models.ManyToManyField(blank=True, related_name='profesores', to='aula_virtual.carreradb')),
                ('cursos', models.ManyToManyField(blank=True, related_name='profesores', to='aula_virtual.cursodb')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.departamentodb')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'profesordb',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='ReservaDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_reserva', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado')], default='disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('aula_virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.aulavirtualdb')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.cursodb')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.profesordb')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservadb',
                'ordering': ['fecha_reserva'],
            },
        ),
    ]
