# Generated by Django 5.2.1 on 2025-05-17 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('jefe', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'DepartamentoDB',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CursoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en horas')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.departamentodb')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'CursoDB',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CarreraDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='aula_virtual.cursodb')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='aula_virtual.departamentodb')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'CarreraDB',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProfesorDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=9, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_ingreso', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cursos', models.ManyToManyField(to='aula_virtual.cursodb')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.departamentodb')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'ProfesorDB',
                'ordering': ['apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Aula_VirtualDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado')], default='disponible', max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_reserva', models.DateField()),
                ('motivo_reserva', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.cursodb')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.profesordb')),
            ],
            options={
                'verbose_name': 'Aula Virtual',
                'verbose_name_plural': 'Aulas Virtuales',
                'db_table': 'Aula_VirtualDB',
                'ordering': ['codigo'],
            },
        ),
    ]
