# Generated by Django 5.2.1 on 2025-05-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aula_VirtualDB',
            new_name='AulaVirtualDB',
        ),
        migrations.AddField(
            model_name='carreradb',
            name='profesores',
            field=models.ManyToManyField(related_name='carreras_profesor', to='aula_virtual.profesordb'),
        ),
        migrations.AddField(
            model_name='profesordb',
            name='carreras',
            field=models.ManyToManyField(related_name='profesores_relacionados', to='aula_virtual.carreradb'),
        ),
        migrations.RemoveField(
            model_name='carreradb',
            name='cursos',
        ),
        migrations.AddField(
            model_name='carreradb',
            name='cursos',
            field=models.ManyToManyField(related_name='carreras', to='aula_virtual.cursodb'),
        ),
    ]
