# Generated by Django 5.2.1 on 2025-07-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reserva',
            new_name='reservadb_fecha_r_0d8b89_idx',
            old_name='reserva_fecha_r_686048_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='reservadb_user_id_9f24d8_idx',
            old_name='reserva_user_id_59a7fc_idx',
        ),
        migrations.AlterModelTable(
            name='aulavirtual',
            table='aula_virtualdb',
        ),
        migrations.AlterModelTable(
            name='calendarioinstitucional',
            table='calendario_institucionaldb',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reservadb',
        ),
    ]
