# Generated by Django 5.2.1 on 2025-05-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0002_rename_aula_virtualdb_aulavirtualdb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursodb',
            name='departamento',
        ),
        migrations.AddField(
            model_name='cursodb',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.carreradb'),
        ),
    ]
