# Generated by Django 5.2.1 on 2025-05-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0003_remove_cursodb_departamento_cursodb_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreradb',
            name='cursos',
            field=models.ManyToManyField(null=True, related_name='carreras', to='aula_virtual.cursodb'),
        ),
    ]
