# Generated by Django 5.2.1 on 2025-05-21 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0004_alter_carreradb_cursos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulavirtualdb',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='aulavirtualdb',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='aulavirtualdb',
            name='fecha_reserva',
        ),
        migrations.RemoveField(
            model_name='aulavirtualdb',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='aulavirtualdb',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='aulavirtualdb',
            name='motivo_reserva',
        ),
        migrations.RemoveField(
            model_name='carreradb',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='carreradb',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='carreradb',
            name='profesores',
        ),
        migrations.RemoveField(
            model_name='departamentodb',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='departamentodb',
            name='jefe',
        ),
        migrations.RemoveField(
            model_name='profesordb',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='profesordb',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profesordb',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='aulavirtualdb',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursodb',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesordb',
            name='nombres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profesordb',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aulavirtualdb',
            name='estado',
            field=models.CharField(blank=True, choices=[('disponible', 'Aula virtual lista para reservar'), ('reservada', 'Aula virtual ya asignada/reservada'), ('en_uso', 'Aula virtual está en uso ahora'), ('en_mantenimiento', 'Aula virtual no disponible por mantenimiento o problemas técnicos'), ('inactiva', 'Aula virtual deshabilitada temporal o permanentemente'), ('bloqueada', 'Aula virtual bloqueada')], default='disponible', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aulavirtualdb',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_virtuales', to='aula_virtual.profesordb'),
        ),
        migrations.AlterField(
            model_name='carreradb',
            name='codigo',
            field=models.CharField(blank=True, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='carreradb',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.departamentodb'),
        ),
        migrations.AlterField(
            model_name='carreradb',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cursodb',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.carreradb'),
        ),
        migrations.AlterField(
            model_name='cursodb',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cursodb',
            name='duracion',
            field=models.PositiveIntegerField(blank=True, help_text='Duración en horas', null=True),
        ),
        migrations.AlterField(
            model_name='cursodb',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='departamentodb',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profesordb',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profesordb',
            name='carreras',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='aula_virtual.carreradb'),
        ),
        migrations.AlterField(
            model_name='profesordb',
            name='codigo',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profesordb',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profesordb',
            name='cursos',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='aula_virtual.cursodb'),
        ),
        migrations.AlterField(
            model_name='profesordb',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.departamentodb'),
        ),
        migrations.CreateModel(
            name='ReservaDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_reserva', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado')], default='disponible', max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('aula_virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.aulavirtualdb')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.cursodb')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula_virtual.profesordb')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'ReservaDB',
                'ordering': ['fecha_reserva'],
            },
        ),
    ]
