# Generated by Django 5.2.1 on 2025-06-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula_virtual', '0005_remove_aulavirtualdb_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulavirtualdb',
            name='profesor',
        ),
        migrations.AlterField(
            model_name='aulavirtualdb',
            name='estado',
            field=models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('en_uso', 'En Uso'), ('en_mantenimiento', 'En_Mantenimiento'), ('inactiva', 'Inactiva'), ('bloqueada', 'Bloqueada')], default='disponible', max_length=20, null=True),
        ),
    ]
