# Generated by Django 5.2.1 on 2025-05-13 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CubiculoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=2, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado')], default='disponible', max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_reserva', models.DateField()),
                ('motivo_reserva', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.cursodb')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.profesordb')),
            ],
            options={
                'verbose_name': 'Cubículo',
                'verbose_name_plural': 'Cubículos',
                'db_table': 'cubiculosDB',
                'ordering': ['codigo'],
            },
        ),
    ]
